version: '{build}'

clone_folder: c:\gopath\src\github.com\AlekSi\gocoverutil

environment:
  GOPATH: c:\gopath

install:
  - set PATH=%PATH%;C:\msys64\mingw64\bin;%GOPATH%\bin
  - go version

  - go get ./...

build_script:
  - mingw32-make install

test_script:
  - mingw32-make

on_success:
  - curl -s -o codecov https://codecov.io/bash
  - bash codecov -X fix -f cover.out
